name: android-tests

on:
  workflow_call:

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: build

      - name: Install dependencies
        run: |
          conda install -y \
            cffi=1.15.1 \
            cmake=3.22.1 \
            mkl=2022.1.0 \
            mkl-include=2022.1.0 \
            ninja=1.10.2 \
            numpy=1.23.3 \
            pyyaml=6.0 \
            requests=2.28.1 \
            setuptools=65.5.0 \
            typing_extensions=4.3.0

      # [see note: pytorch repo ref]
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master

      - name: Build PyTorch Android
        run: |
          # Install NDK 21 after GitHub update
          # https://github.com/actions/virtual-environments/issues/5595
          ANDROID_ROOT="/usr/local/lib/android"
          ANDROID_SDK_ROOT="${ANDROID_ROOT}/sdk"
          SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
          echo "y" | ${SDKMANAGER} "ndk;21.4.7075529"

          export ANDROID_NDK="${ANDROID_SDK_ROOT}/ndk-bundle"
          ln -sfn ${ANDROID_SDK_ROOT}/ndk/21.4.7075529 ${ANDROID_NDK}

          echo "CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname "$(which conda)")/../"}" >> "${GITHUB_ENV}"
          ./scripts/build_pytorch_android.sh x86

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 25
          script: ./android/run_tests.sh
